# Generated by Django 5.2.1 on 2025-06-10 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_variationcombination'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='variationcombination',
            name='stock',
        ),
        migrations.AddField(
            model_name='variationcombination',
            name='stock_per_category',
            field=models.JSONField(default=dict),
        ),
    ]
