# Generated by Django 5.2 on 2025-06-12 06:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_remove_variationcombination_stock_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
        migrations.RemoveField(
            model_name='variation',
            name='product',
        ),
        migrations.RemoveField(
            model_name='variationcombination',
            name='product',
        ),
        migrations.RemoveField(
            model_name='variationcombination',
            name='variations',
        ),
    ]
