# Generated by Django 5.2 on 2025-07-03 14:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_variationcategory_alter_variation_variation_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='variationcategory',
            options={'verbose_name': 'Variation Category', 'verbose_name_plural': 'Variation Categories'},
        ),
    ]
