# Generated by Django 5.2 on 2025-06-12 06:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0006_alter_cartitem_product_alter_cartitem_variations'),
        ('orders', '0014_alter_orderproduct_product_and_more'),
        ('store', '0005_remove_product_category_remove_variation_product_and_more'),
        ('vendor', '0002_remove_vendorvariationcombination_vendor_product_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Product',
        ),
        migrations.DeleteModel(
            name='Variation',
        ),
        migrations.DeleteModel(
            name='VariationCombination',
        ),
    ]
