# Generated by Django 5.2 on 2025-07-03 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_alter_variation_variation_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='variation',
            name='tock',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
