# Generated by Django 5.2 on 2025-07-03 22:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_variation_tock'),
    ]

    operations = [
        migrations.RenameField(
            model_name='variation',
            old_name='tock',
            new_name='stock',
        ),
    ]
