# Generated by Django 5.2 on 2025-07-04 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0014_product_product_type_alter_product_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variation',
            name='stock',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
    ]
