# Generated by Django 5.2 on 2025-07-06 00:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0015_alter_variation_stock'),
    ]

    operations = [
        migrations.CreateModel(
            name='PricingRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_type', models.CharField(blank=True, choices=[('simple', 'Simple'), ('variation', 'Variation'), ('combination', 'Combination')], help_text='Optional: restrict rule to a product type', max_length=20, null=True)),
                ('category', models.CharField(max_length=100)),
                ('value', models.CharField(max_length=100)),
                ('price_adjustment', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'verbose_name': 'Pricing Rule',
                'verbose_name_plural': 'Pricing Rules',
                'ordering': ['category', 'value'],
            },
        ),
        migrations.CreateModel(
            name='VariationOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=100)),
                ('values', models.TextField(help_text='Comma-separated values, e.g. Red, Blue, Green')),
            ],
        ),
        migrations.CreateModel(
            name='VariationOptionSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='variationcombination',
            name='sku',
            field=models.CharField(blank=True, max_length=200, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='stock',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddIndex(
            model_name='variationcombination',
            index=models.Index(fields=['product'], name='store_varia_product_84396a_idx'),
        ),
        migrations.AddIndex(
            model_name='variationcombination',
            index=models.Index(fields=['sku'], name='store_varia_sku_f0c349_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='pricingrule',
            unique_together={('product_type', 'category', 'value')},
        ),
        migrations.AddField(
            model_name='variationoptionset',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variation_option_sets', to='store.product'),
        ),
        migrations.AddField(
            model_name='variationoption',
            name='set',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='store.variationoptionset'),
        ),
    ]
