# Generated by Django 5.2 on 2025-07-06 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0016_pricingrule_variationoption_variationoptionset_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='variation',
            name='is_variation_enabled',
            field=models.BooleanField(default=False),
        ),
    ]
