# Generated by Django 5.2 on 2025-07-06 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0017_variation_is_variation_enabled'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='variation',
            name='is_variation_enabled',
        ),
        migrations.AddField(
            model_name='product',
            name='is_variation_enabled',
            field=models.BooleanField(default=False, help_text='Show in variation setup dropdown'),
        ),
    ]
