# Generated by Django 5.2 on 2025-07-07 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0018_remove_variation_is_variation_enabled_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='variationoption',
            name='category',
        ),
        migrations.AddField(
            model_name='variationoption',
            name='variation_type',
            field=models.CharField(default='color', help_text='e.g. Color, Size, Material', max_length=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='is_variation_enabled',
            field=models.BooleanField(default=False, help_text='Indicates this product supports variation combinations'),
        ),
    ]
