# Generated by Django 5.2 on 2025-07-07 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0019_remove_variationoption_category_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pricingrule',
            options={'ordering': ['variation_type', 'value'], 'verbose_name': 'Pricing Rule', 'verbose_name_plural': 'Pricing Rules'},
        ),
        migrations.RenameField(
            model_name='pricingrule',
            old_name='category',
            new_name='variation_type',
        ),
        migrations.RenameField(
            model_name='variation',
            old_name='variation_category',
            new_name='variation_type',
        ),
        migrations.AlterField(
            model_name='variationoption',
            name='variation_type',
            field=models.CharField(blank=True, help_text='e.g. Color, Size, Material', max_length=100, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='pricingrule',
            unique_together={('product_type', 'variation_type', 'value')},
        ),
    ]
