# Generated by Django 5.2 on 2025-07-07 08:41

from django.db import migrations

def backfill_variation_fields(apps, schema_editor):
    Variation = apps.get_model('store', 'Variation')
    VariationOption = apps.get_model('store', 'VariationOption')

    # 1. Sync variation_type for Variation instances
    for v in Variation.objects.all():
        if not v.variation_type:
            # Fallback default or smarter pattern match
            v.variation_type = "Color"
            v.save()

    # 2. Sync variation_type for VariationOption instances
    for option in VariationOption.objects.all():
        if not option.variation_type:
            option.variation_type = "Color"
            option.save()

class Migration(migrations.Migration):

    dependencies = [
        ('store', '0020_alter_pricingrule_options_and_more'),
    ]

    operations = [
        migrations.RunPython(backfill_variation_fields),
    ]