# Generated by Django 5.2 on 2025-07-07 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0021_auto_20250707_0941'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variationoption',
            name='variation_type',
            field=models.CharField(help_text='e.g. Color, Size, Material', max_length=100),
        ),
    ]
