# Generated by Django 5.2 on 2025-07-07 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0022_alter_variationoption_variation_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pricingrule',
            name='product_type',
            field=models.CharField(blank=True, choices=[('simple', 'Simple (no variations)'), ('variation', 'Product with individual variations'), ('combination', 'Product with variation combinations')], help_text='Optionally restrict pricing rule to a product type', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='is_variation_enabled',
            field=models.BooleanField(default=False, help_text='Indicates whether this product supports variation combinations'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_type',
            field=models.CharField(choices=[('simple', 'Simple (no variations)'), ('variation', 'Product with individual variations'), ('combination', 'Product with variation combinations')], default='simple', max_length=20),
        ),
        migrations.AlterField(
            model_name='variation',
            name='variation_type',
            field=models.CharField(help_text='e.g. Color, Size', max_length=100),
        ),
        migrations.AlterField(
            model_name='variationoption',
            name='values',
            field=models.TextField(help_text='Comma-separated values (e.g. Red, Blue, Green)'),
        ),
        migrations.AddIndex(
            model_name='variation',
            index=models.Index(fields=['product'], name='store_varia_product_bba665_idx'),
        ),
        migrations.AddIndex(
            model_name='variation',
            index=models.Index(fields=['variation_type'], name='store_varia_variati_239e67_idx'),
        ),
        migrations.AddIndex(
            model_name='variation',
            index=models.Index(fields=['is_active'], name='store_varia_is_acti_cb315f_idx'),
        ),
        migrations.AddIndex(
            model_name='variationcombination',
            index=models.Index(fields=['is_active'], name='store_varia_is_acti_a077c7_idx'),
        ),
    ]
