# Generated by Django 5.2 on 2025-07-08 17:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0023_alter_pricingrule_product_type_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='variation',
            options={'ordering': ['variation_type', 'variation_value']},
        ),
        migrations.RemoveIndex(
            model_name='variation',
            name='store_varia_product_bba665_idx',
        ),
        migrations.RemoveIndex(
            model_name='variation',
            name='store_varia_variati_239e67_idx',
        ),
        migrations.RemoveIndex(
            model_name='variation',
            name='store_varia_is_acti_cb315f_idx',
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=15),
        ),
        migrations.AlterField(
            model_name='variation',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='variation',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='variation',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variations', to='store.product'),
        ),
        migrations.AlterField(
            model_name='variation',
            name='stock',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='variation',
            name='variation_type',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='variation',
            name='variation_value',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='variationcombination',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=15),
        ),
        migrations.AlterUniqueTogether(
            name='variation',
            unique_together={('product', 'variation_type', 'variation_value')},
        ),
    ]
