# Generated by Django 5.2 on 2025-07-08 18:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0024_alter_variation_options_and_more'),
    ]

    operations = [
        # migrations.RemoveConstraint(
        #     model_name='variationcombination',
        #     name='unique_combo_per_product',
        # ),
    ]
