# Generated by Django 5.2.1 on 2025-05-21 06:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0002_remove_cartitem_date_added'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='card_id',
            new_name='cart_id',
        ),
    ]
