# Generated by Django 5.2 on 2025-07-10 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_account_groups_account_is_vendor_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='is_vendor',
        ),
        migrations.AddField(
            model_name='account',
            name='role',
            field=models.CharField(choices=[('vendor', 'Vendor'), ('customer', 'Customer')], default='customer', max_length=10),
        ),
    ]
