"""
Django settings for pogosmarketplace project.

Generated by 'django-admin startproject' using Django 5.2.1.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-&w#0qbzb#%$9@iw*)1clrqd-yqguo7_bj@su1&26^z&d)0x89m'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'category',
    'accounts',
    'store',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'pogosmarketplace.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': ['templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',

                # This is the context processor that adds the list of categories to the context of all templates
                'category.context_processors.menu_links',  
            ],
        },
    },
]

WSGI_APPLICATION = 'pogosmarketplace.wsgi.application'


# We are telling this 'settings.py' file that we are using a custom user model(instead of the default django admin user model) which we created in 'account' app model:
AUTH_USER_MODEL = 'accounts.Account'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/


# The below URL is where the static files will be served from in development. It is the URL prefix for static files, for example, if you have static files in a directory called 'pogosmarketplace/static' in your project, they will be collected from 'pogosmarketplace/static/css/style.css' into the 'STATIC_ROOT = BASE_DIR / 'static'' and accessible at 'http://localhost:8000/static/css/style.css' after running the development server.
STATIC_URL = '/static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field


# The below is where all the static files from 'STATICFILES_DIRS' will be collected to when you run the 'python manage.py collectstatic' command. This folder gets created automatically when you run the command 'python manage.py collectstatic'. It is the location where all static files are collected for production use.
STATIC_ROOT = BASE_DIR /'static'


# The below is where Django will look for static files in your project. You can add multiple directories here, and Django will look in each of them for static files. The paths should be relative to the base directory of your project.
# For example, if you have a directory called 'pogosmarketplace/static' in your project, you would add it here. This is where Django will look for static files when you run the command ''python manage.py collectstatic' in development server.
STATICFILES_DIRS = [
    'pogosmarketplace/static',
]


# Media files configuration

# # The below URL is where the media files will be served from in development. It is the URL prefix for media files,.
MEDIA_URL = '/media/'

MEDIA_ROOT = BASE_DIR /'media'


DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
