# Generated by Django 5.2.1 on 2025-06-09 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_alter_payment_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed'), ('DECLINED', 'Declined'), ('CANCELLED', 'Cancelled'), ('REFUNDED', 'Refunded'), ('PARTIALLY_REFUNDED', 'Partially_Refunded'), ('AUTHORIZED', 'Authorized'), ('CAPTURED', 'Captured'), ('EXPIRED', 'Expired'), ('REVERSED', 'Reversed')], default='PENDING', max_length=20),
        ),
    ]
